// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/local/objectbox_entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1177744648965105105),
    name: 'ActivityEntity',
    lastPropertyId: const obx_int.IdUid(20, 7461268415209189369),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8778573185472787521),
        name: 'obId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4719042315109416006),
        name: 'id',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 7522082869226596497),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8756660519665580926),
        name: 'category',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 1396078899304996528),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3257976015480699967),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2286503921366683063),
        name: 'rating',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6739631771871497563),
        name: 'price',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7596834490243837588),
        name: 'imageUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1992361276795275736),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1238615804383927996),
        name: 'locationLat',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 310613890271212786),
        name: 'locationLng',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 2402519268050837384),
        name: 'locationCity',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 2914608329016245872),
        name: 'locationCountry',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 8902364065295894646),
        name: 'locationAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 1254822379872644137),
        name: 'currency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 629904717446175662),
        name: 'bookingUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 7461268415209189369),
        name: 'duration',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 439500610461656578),
    name: 'FlightEntity',
    lastPropertyId: const obx_int.IdUid(22, 7424731035771837360),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7995408394231881418),
        name: 'obId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 245841516169853154),
        name: 'id',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 3962381625223895775),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7639639452830714420),
        name: 'departureCity',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5145104778837089939),
        name: 'arrivalCity',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3977179447163624261),
        name: 'departureTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3760929323790350302),
        name: 'arrivalTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2427098819330120203),
        name: 'airline',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8641096524469099735),
        name: 'flightNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1094857642960131131),
        name: 'price',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3063338003980470536),
        name: 'duration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6080464898868309150),
        name: 'departureCountry',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1224184235947936808),
        name: 'arrivalCountry',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6152524373338742497),
        name: 'departureLat',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 427195408208592780),
        name: 'departureLng',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 180178431754849293),
        name: 'arrivalLat',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 8540234879602188945),
        name: 'arrivalLng',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 7371038362405728727),
        name: 'currency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 197649080309652923),
        name: 'departureAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 8438913456189543822),
        name: 'arrivalAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 7424731035771837360),
        name: 'bookingUrl',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 5530193129808549760),
    name: 'HotelEntity',
    lastPropertyId: const obx_int.IdUid(20, 7157188039317842283),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 676950049499059522),
        name: 'obId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 783406188880043578),
        name: 'id',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 1841845370702993087),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3956169394236615464),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7225378485096539889),
        name: 'locationCity',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 999938264386687520),
        name: 'locationCountry',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1178598269793947819),
        name: 'pricePerNight',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 301310274451217192),
        name: 'rating',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5935809462688905894),
        name: 'imageUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 5243447832368914700),
        name: 'locationLat',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 4855197630061792073),
        name: 'locationLng',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 5390324021009779286),
        name: 'locationAddress',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 7278549921212330588),
        name: 'reviewCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 2204863057993176357),
        name: 'currency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 9160797143189118113),
        name: 'amenitiesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 1346485467024991966),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 7157188039317842283),
        name: 'bookingUrl',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 7523196917833823992),
    name: 'TripEntity',
    lastPropertyId: const obx_int.IdUid(21, 3850833962395947546),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6182459024848328067),
        name: 'obId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5677892199470614175),
        name: 'id',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(6, 7936909492237569737),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6484072496346271131),
        name: 'userId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 4898886470961329948),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6051730051809878296),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1780293688210280093),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7550100048141962050),
        name: 'destination',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4279592102739015424),
        name: 'startDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 322776346779254467),
        name: 'endDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8561535552782112758),
        name: 'destinationsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 587228651891135154),
        name: 'outboundFlightJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5141915203813540591),
        name: 'returnFlightJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 9221081432676984011),
        name: 'hotelsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 269151628929529783),
        name: 'activitiesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 5697978856421254223),
        name: 'itineraryJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 5548436890415307865),
        name: 'budgetJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 4206467204540054792),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 6456835929916875157),
        name: 'numberOfPeople',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 4982628142004116468),
        name: 'coverImageUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 8751761396668995264),
        name: 'tagsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 8477779489060880572),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 3850833962395947546),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 7523196917833823992),
    lastIndexId: const obx_int.IdUid(7, 4898886470961329948),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [4439324196752511960],
    retiredPropertyUids: const [
      2548055212301095521,
      7582911451408340119,
      3413554608561557053,
      7477183441675183218,
      8779893068996924299,
      4854991665655760362,
      9173206138200804895,
      7820877097142233230,
      7161266595123402486,
      6669697208199640247,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ActivityEntity: obx_int.EntityDefinition<ActivityEntity>(
      model: _entities[0],
      toOneRelations: (ActivityEntity object) => [],
      toManyRelations: (ActivityEntity object) => {},
      getId: (ActivityEntity object) => object.obId,
      setId: (ActivityEntity object, int id) {
        object.obId = id;
      },
      objectToFB: (ActivityEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final categoryOffset = fbb.writeString(object.category);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final imageUrlOffset = object.imageUrl == null
            ? null
            : fbb.writeString(object.imageUrl!);
        final nameOffset = fbb.writeString(object.name);
        final locationCityOffset = object.locationCity == null
            ? null
            : fbb.writeString(object.locationCity!);
        final locationCountryOffset = object.locationCountry == null
            ? null
            : fbb.writeString(object.locationCountry!);
        final locationAddressOffset = object.locationAddress == null
            ? null
            : fbb.writeString(object.locationAddress!);
        final currencyOffset = fbb.writeString(object.currency);
        final bookingUrlOffset = object.bookingUrl == null
            ? null
            : fbb.writeString(object.bookingUrl!);
        fbb.startTable(21);
        fbb.addInt64(0, object.obId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(3, categoryOffset);
        fbb.addOffset(4, descriptionOffset);
        fbb.addFloat64(5, object.rating);
        fbb.addFloat64(6, object.price);
        fbb.addOffset(9, imageUrlOffset);
        fbb.addOffset(11, nameOffset);
        fbb.addFloat64(12, object.locationLat);
        fbb.addFloat64(13, object.locationLng);
        fbb.addOffset(14, locationCityOffset);
        fbb.addOffset(15, locationCountryOffset);
        fbb.addOffset(16, locationAddressOffset);
        fbb.addOffset(17, currencyOffset);
        fbb.addOffset(18, bookingUrlOffset);
        fbb.addInt64(19, object.duration);
        fbb.finish(fbb.endTable());
        return object.obId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ActivityEntity()
          ..obId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..id = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..category = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..description = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 12)
          ..rating = const fb.Float64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            14,
          )
          ..price = const fb.Float64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            16,
          )
          ..imageUrl = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 22)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 26, '')
          ..locationLat = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            28,
            0,
          )
          ..locationLng = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            30,
            0,
          )
          ..locationCity = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 32)
          ..locationCountry = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 34)
          ..locationAddress = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 36)
          ..currency = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 38, '')
          ..bookingUrl = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 40)
          ..duration = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            42,
          );

        return object;
      },
    ),
    FlightEntity: obx_int.EntityDefinition<FlightEntity>(
      model: _entities[1],
      toOneRelations: (FlightEntity object) => [],
      toManyRelations: (FlightEntity object) => {},
      getId: (FlightEntity object) => object.obId,
      setId: (FlightEntity object, int id) {
        object.obId = id;
      },
      objectToFB: (FlightEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final departureCityOffset = fbb.writeString(object.departureCity);
        final arrivalCityOffset = fbb.writeString(object.arrivalCity);
        final airlineOffset = fbb.writeString(object.airline);
        final flightNumberOffset = object.flightNumber == null
            ? null
            : fbb.writeString(object.flightNumber!);
        final departureCountryOffset = object.departureCountry == null
            ? null
            : fbb.writeString(object.departureCountry!);
        final arrivalCountryOffset = object.arrivalCountry == null
            ? null
            : fbb.writeString(object.arrivalCountry!);
        final currencyOffset = object.currency == null
            ? null
            : fbb.writeString(object.currency!);
        final departureAddressOffset = object.departureAddress == null
            ? null
            : fbb.writeString(object.departureAddress!);
        final arrivalAddressOffset = object.arrivalAddress == null
            ? null
            : fbb.writeString(object.arrivalAddress!);
        final bookingUrlOffset = object.bookingUrl == null
            ? null
            : fbb.writeString(object.bookingUrl!);
        fbb.startTable(23);
        fbb.addInt64(0, object.obId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, departureCityOffset);
        fbb.addOffset(3, arrivalCityOffset);
        fbb.addInt64(4, object.departureTime.millisecondsSinceEpoch);
        fbb.addInt64(5, object.arrivalTime.millisecondsSinceEpoch);
        fbb.addOffset(6, airlineOffset);
        fbb.addOffset(7, flightNumberOffset);
        fbb.addFloat64(8, object.price);
        fbb.addInt64(9, object.duration);
        fbb.addOffset(11, departureCountryOffset);
        fbb.addOffset(12, arrivalCountryOffset);
        fbb.addFloat64(13, object.departureLat);
        fbb.addFloat64(14, object.departureLng);
        fbb.addFloat64(15, object.arrivalLat);
        fbb.addFloat64(16, object.arrivalLng);
        fbb.addOffset(17, currencyOffset);
        fbb.addOffset(19, departureAddressOffset);
        fbb.addOffset(20, arrivalAddressOffset);
        fbb.addOffset(21, bookingUrlOffset);
        fbb.finish(fbb.endTable());
        return object.obId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = FlightEntity()
          ..obId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..id = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..departureCity = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..arrivalCity = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..departureTime = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
          )
          ..arrivalTime = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
          )
          ..airline = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..flightNumber = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 18)
          ..price = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            20,
            0,
          )
          ..duration = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            22,
            0,
          )
          ..departureCountry = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 26)
          ..arrivalCountry = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 28)
          ..departureLat = const fb.Float64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            30,
          )
          ..departureLng = const fb.Float64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            32,
          )
          ..arrivalLat = const fb.Float64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            34,
          )
          ..arrivalLng = const fb.Float64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            36,
          )
          ..currency = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 38)
          ..departureAddress = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 42)
          ..arrivalAddress = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 44)
          ..bookingUrl = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 46);

        return object;
      },
    ),
    HotelEntity: obx_int.EntityDefinition<HotelEntity>(
      model: _entities[2],
      toOneRelations: (HotelEntity object) => [],
      toManyRelations: (HotelEntity object) => {},
      getId: (HotelEntity object) => object.obId,
      setId: (HotelEntity object, int id) {
        object.obId = id;
      },
      objectToFB: (HotelEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final nameOffset = fbb.writeString(object.name);
        final locationCityOffset = object.locationCity == null
            ? null
            : fbb.writeString(object.locationCity!);
        final locationCountryOffset = object.locationCountry == null
            ? null
            : fbb.writeString(object.locationCountry!);
        final imageUrlOffset = object.imageUrl == null
            ? null
            : fbb.writeString(object.imageUrl!);
        final locationAddressOffset = object.locationAddress == null
            ? null
            : fbb.writeString(object.locationAddress!);
        final currencyOffset = fbb.writeString(object.currency);
        final amenitiesJsonOffset = fbb.writeString(object.amenitiesJson);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final bookingUrlOffset = object.bookingUrl == null
            ? null
            : fbb.writeString(object.bookingUrl!);
        fbb.startTable(21);
        fbb.addInt64(0, object.obId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, locationCityOffset);
        fbb.addOffset(4, locationCountryOffset);
        fbb.addFloat64(6, object.pricePerNight);
        fbb.addFloat64(7, object.rating);
        fbb.addOffset(10, imageUrlOffset);
        fbb.addFloat64(12, object.locationLat);
        fbb.addFloat64(13, object.locationLng);
        fbb.addOffset(14, locationAddressOffset);
        fbb.addInt64(15, object.reviewCount);
        fbb.addOffset(16, currencyOffset);
        fbb.addOffset(17, amenitiesJsonOffset);
        fbb.addOffset(18, descriptionOffset);
        fbb.addOffset(19, bookingUrlOffset);
        fbb.finish(fbb.endTable());
        return object.obId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = HotelEntity()
          ..obId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..id = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..locationCity = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 10)
          ..locationCountry = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 12)
          ..pricePerNight = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          )
          ..rating = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            18,
            0,
          )
          ..imageUrl = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 24)
          ..locationLat = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            28,
            0,
          )
          ..locationLng = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            30,
            0,
          )
          ..locationAddress = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 32)
          ..reviewCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            34,
            0,
          )
          ..currency = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 36, '')
          ..amenitiesJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 38, '')
          ..description = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 40)
          ..bookingUrl = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 42);

        return object;
      },
    ),
    TripEntity: obx_int.EntityDefinition<TripEntity>(
      model: _entities[3],
      toOneRelations: (TripEntity object) => [],
      toManyRelations: (TripEntity object) => {},
      getId: (TripEntity object) => object.obId,
      setId: (TripEntity object, int id) {
        object.obId = id;
      },
      objectToFB: (TripEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final userIdOffset = fbb.writeString(object.userId);
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final destinationOffset = fbb.writeString(object.destination);
        final destinationsJsonOffset = fbb.writeString(object.destinationsJson);
        final outboundFlightJsonOffset = object.outboundFlightJson == null
            ? null
            : fbb.writeString(object.outboundFlightJson!);
        final returnFlightJsonOffset = object.returnFlightJson == null
            ? null
            : fbb.writeString(object.returnFlightJson!);
        final hotelsJsonOffset = object.hotelsJson == null
            ? null
            : fbb.writeString(object.hotelsJson!);
        final activitiesJsonOffset = object.activitiesJson == null
            ? null
            : fbb.writeString(object.activitiesJson!);
        final itineraryJsonOffset = fbb.writeString(object.itineraryJson);
        final budgetJsonOffset = object.budgetJson == null
            ? null
            : fbb.writeString(object.budgetJson!);
        final statusOffset = fbb.writeString(object.status);
        final coverImageUrlOffset = object.coverImageUrl == null
            ? null
            : fbb.writeString(object.coverImageUrl!);
        final tagsJsonOffset = fbb.writeString(object.tagsJson);
        fbb.startTable(22);
        fbb.addInt64(0, object.obId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, userIdOffset);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(4, descriptionOffset);
        fbb.addOffset(5, destinationOffset);
        fbb.addInt64(6, object.startDate.millisecondsSinceEpoch);
        fbb.addInt64(7, object.endDate.millisecondsSinceEpoch);
        fbb.addOffset(8, destinationsJsonOffset);
        fbb.addOffset(9, outboundFlightJsonOffset);
        fbb.addOffset(10, returnFlightJsonOffset);
        fbb.addOffset(11, hotelsJsonOffset);
        fbb.addOffset(12, activitiesJsonOffset);
        fbb.addOffset(13, itineraryJsonOffset);
        fbb.addOffset(14, budgetJsonOffset);
        fbb.addOffset(15, statusOffset);
        fbb.addInt64(16, object.numberOfPeople);
        fbb.addOffset(17, coverImageUrlOffset);
        fbb.addOffset(18, tagsJsonOffset);
        fbb.addInt64(19, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(20, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.obId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = TripEntity()
          ..obId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..id = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..userId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..description = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 12)
          ..destination = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..startDate = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
          )
          ..endDate = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
          )
          ..destinationsJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '')
          ..outboundFlightJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 22)
          ..returnFlightJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 24)
          ..hotelsJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 26)
          ..activitiesJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 28)
          ..itineraryJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 30, '')
          ..budgetJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 32)
          ..status = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 34, '')
          ..numberOfPeople = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            36,
            0,
          )
          ..coverImageUrl = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 38)
          ..tagsJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 40, '')
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 42, 0),
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 44, 0),
          );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ActivityEntity] entity fields to define ObjectBox queries.
class ActivityEntity_ {
  /// See [ActivityEntity.obId].
  static final obId = obx.QueryIntegerProperty<ActivityEntity>(
    _entities[0].properties[0],
  );

  /// See [ActivityEntity.id].
  static final id = obx.QueryStringProperty<ActivityEntity>(
    _entities[0].properties[1],
  );

  /// See [ActivityEntity.category].
  static final category = obx.QueryStringProperty<ActivityEntity>(
    _entities[0].properties[2],
  );

  /// See [ActivityEntity.description].
  static final description = obx.QueryStringProperty<ActivityEntity>(
    _entities[0].properties[3],
  );

  /// See [ActivityEntity.rating].
  static final rating = obx.QueryDoubleProperty<ActivityEntity>(
    _entities[0].properties[4],
  );

  /// See [ActivityEntity.price].
  static final price = obx.QueryDoubleProperty<ActivityEntity>(
    _entities[0].properties[5],
  );

  /// See [ActivityEntity.imageUrl].
  static final imageUrl = obx.QueryStringProperty<ActivityEntity>(
    _entities[0].properties[6],
  );

  /// See [ActivityEntity.name].
  static final name = obx.QueryStringProperty<ActivityEntity>(
    _entities[0].properties[7],
  );

  /// See [ActivityEntity.locationLat].
  static final locationLat = obx.QueryDoubleProperty<ActivityEntity>(
    _entities[0].properties[8],
  );

  /// See [ActivityEntity.locationLng].
  static final locationLng = obx.QueryDoubleProperty<ActivityEntity>(
    _entities[0].properties[9],
  );

  /// See [ActivityEntity.locationCity].
  static final locationCity = obx.QueryStringProperty<ActivityEntity>(
    _entities[0].properties[10],
  );

  /// See [ActivityEntity.locationCountry].
  static final locationCountry = obx.QueryStringProperty<ActivityEntity>(
    _entities[0].properties[11],
  );

  /// See [ActivityEntity.locationAddress].
  static final locationAddress = obx.QueryStringProperty<ActivityEntity>(
    _entities[0].properties[12],
  );

  /// See [ActivityEntity.currency].
  static final currency = obx.QueryStringProperty<ActivityEntity>(
    _entities[0].properties[13],
  );

  /// See [ActivityEntity.bookingUrl].
  static final bookingUrl = obx.QueryStringProperty<ActivityEntity>(
    _entities[0].properties[14],
  );

  /// See [ActivityEntity.duration].
  static final duration = obx.QueryIntegerProperty<ActivityEntity>(
    _entities[0].properties[15],
  );
}

/// [FlightEntity] entity fields to define ObjectBox queries.
class FlightEntity_ {
  /// See [FlightEntity.obId].
  static final obId = obx.QueryIntegerProperty<FlightEntity>(
    _entities[1].properties[0],
  );

  /// See [FlightEntity.id].
  static final id = obx.QueryStringProperty<FlightEntity>(
    _entities[1].properties[1],
  );

  /// See [FlightEntity.departureCity].
  static final departureCity = obx.QueryStringProperty<FlightEntity>(
    _entities[1].properties[2],
  );

  /// See [FlightEntity.arrivalCity].
  static final arrivalCity = obx.QueryStringProperty<FlightEntity>(
    _entities[1].properties[3],
  );

  /// See [FlightEntity.departureTime].
  static final departureTime = obx.QueryDateProperty<FlightEntity>(
    _entities[1].properties[4],
  );

  /// See [FlightEntity.arrivalTime].
  static final arrivalTime = obx.QueryDateProperty<FlightEntity>(
    _entities[1].properties[5],
  );

  /// See [FlightEntity.airline].
  static final airline = obx.QueryStringProperty<FlightEntity>(
    _entities[1].properties[6],
  );

  /// See [FlightEntity.flightNumber].
  static final flightNumber = obx.QueryStringProperty<FlightEntity>(
    _entities[1].properties[7],
  );

  /// See [FlightEntity.price].
  static final price = obx.QueryDoubleProperty<FlightEntity>(
    _entities[1].properties[8],
  );

  /// See [FlightEntity.duration].
  static final duration = obx.QueryIntegerProperty<FlightEntity>(
    _entities[1].properties[9],
  );

  /// See [FlightEntity.departureCountry].
  static final departureCountry = obx.QueryStringProperty<FlightEntity>(
    _entities[1].properties[10],
  );

  /// See [FlightEntity.arrivalCountry].
  static final arrivalCountry = obx.QueryStringProperty<FlightEntity>(
    _entities[1].properties[11],
  );

  /// See [FlightEntity.departureLat].
  static final departureLat = obx.QueryDoubleProperty<FlightEntity>(
    _entities[1].properties[12],
  );

  /// See [FlightEntity.departureLng].
  static final departureLng = obx.QueryDoubleProperty<FlightEntity>(
    _entities[1].properties[13],
  );

  /// See [FlightEntity.arrivalLat].
  static final arrivalLat = obx.QueryDoubleProperty<FlightEntity>(
    _entities[1].properties[14],
  );

  /// See [FlightEntity.arrivalLng].
  static final arrivalLng = obx.QueryDoubleProperty<FlightEntity>(
    _entities[1].properties[15],
  );

  /// See [FlightEntity.currency].
  static final currency = obx.QueryStringProperty<FlightEntity>(
    _entities[1].properties[16],
  );

  /// See [FlightEntity.departureAddress].
  static final departureAddress = obx.QueryStringProperty<FlightEntity>(
    _entities[1].properties[17],
  );

  /// See [FlightEntity.arrivalAddress].
  static final arrivalAddress = obx.QueryStringProperty<FlightEntity>(
    _entities[1].properties[18],
  );

  /// See [FlightEntity.bookingUrl].
  static final bookingUrl = obx.QueryStringProperty<FlightEntity>(
    _entities[1].properties[19],
  );
}

/// [HotelEntity] entity fields to define ObjectBox queries.
class HotelEntity_ {
  /// See [HotelEntity.obId].
  static final obId = obx.QueryIntegerProperty<HotelEntity>(
    _entities[2].properties[0],
  );

  /// See [HotelEntity.id].
  static final id = obx.QueryStringProperty<HotelEntity>(
    _entities[2].properties[1],
  );

  /// See [HotelEntity.name].
  static final name = obx.QueryStringProperty<HotelEntity>(
    _entities[2].properties[2],
  );

  /// See [HotelEntity.locationCity].
  static final locationCity = obx.QueryStringProperty<HotelEntity>(
    _entities[2].properties[3],
  );

  /// See [HotelEntity.locationCountry].
  static final locationCountry = obx.QueryStringProperty<HotelEntity>(
    _entities[2].properties[4],
  );

  /// See [HotelEntity.pricePerNight].
  static final pricePerNight = obx.QueryDoubleProperty<HotelEntity>(
    _entities[2].properties[5],
  );

  /// See [HotelEntity.rating].
  static final rating = obx.QueryDoubleProperty<HotelEntity>(
    _entities[2].properties[6],
  );

  /// See [HotelEntity.imageUrl].
  static final imageUrl = obx.QueryStringProperty<HotelEntity>(
    _entities[2].properties[7],
  );

  /// See [HotelEntity.locationLat].
  static final locationLat = obx.QueryDoubleProperty<HotelEntity>(
    _entities[2].properties[8],
  );

  /// See [HotelEntity.locationLng].
  static final locationLng = obx.QueryDoubleProperty<HotelEntity>(
    _entities[2].properties[9],
  );

  /// See [HotelEntity.locationAddress].
  static final locationAddress = obx.QueryStringProperty<HotelEntity>(
    _entities[2].properties[10],
  );

  /// See [HotelEntity.reviewCount].
  static final reviewCount = obx.QueryIntegerProperty<HotelEntity>(
    _entities[2].properties[11],
  );

  /// See [HotelEntity.currency].
  static final currency = obx.QueryStringProperty<HotelEntity>(
    _entities[2].properties[12],
  );

  /// See [HotelEntity.amenitiesJson].
  static final amenitiesJson = obx.QueryStringProperty<HotelEntity>(
    _entities[2].properties[13],
  );

  /// See [HotelEntity.description].
  static final description = obx.QueryStringProperty<HotelEntity>(
    _entities[2].properties[14],
  );

  /// See [HotelEntity.bookingUrl].
  static final bookingUrl = obx.QueryStringProperty<HotelEntity>(
    _entities[2].properties[15],
  );
}

/// [TripEntity] entity fields to define ObjectBox queries.
class TripEntity_ {
  /// See [TripEntity.obId].
  static final obId = obx.QueryIntegerProperty<TripEntity>(
    _entities[3].properties[0],
  );

  /// See [TripEntity.id].
  static final id = obx.QueryStringProperty<TripEntity>(
    _entities[3].properties[1],
  );

  /// See [TripEntity.userId].
  static final userId = obx.QueryStringProperty<TripEntity>(
    _entities[3].properties[2],
  );

  /// See [TripEntity.name].
  static final name = obx.QueryStringProperty<TripEntity>(
    _entities[3].properties[3],
  );

  /// See [TripEntity.description].
  static final description = obx.QueryStringProperty<TripEntity>(
    _entities[3].properties[4],
  );

  /// See [TripEntity.destination].
  static final destination = obx.QueryStringProperty<TripEntity>(
    _entities[3].properties[5],
  );

  /// See [TripEntity.startDate].
  static final startDate = obx.QueryDateProperty<TripEntity>(
    _entities[3].properties[6],
  );

  /// See [TripEntity.endDate].
  static final endDate = obx.QueryDateProperty<TripEntity>(
    _entities[3].properties[7],
  );

  /// See [TripEntity.destinationsJson].
  static final destinationsJson = obx.QueryStringProperty<TripEntity>(
    _entities[3].properties[8],
  );

  /// See [TripEntity.outboundFlightJson].
  static final outboundFlightJson = obx.QueryStringProperty<TripEntity>(
    _entities[3].properties[9],
  );

  /// See [TripEntity.returnFlightJson].
  static final returnFlightJson = obx.QueryStringProperty<TripEntity>(
    _entities[3].properties[10],
  );

  /// See [TripEntity.hotelsJson].
  static final hotelsJson = obx.QueryStringProperty<TripEntity>(
    _entities[3].properties[11],
  );

  /// See [TripEntity.activitiesJson].
  static final activitiesJson = obx.QueryStringProperty<TripEntity>(
    _entities[3].properties[12],
  );

  /// See [TripEntity.itineraryJson].
  static final itineraryJson = obx.QueryStringProperty<TripEntity>(
    _entities[3].properties[13],
  );

  /// See [TripEntity.budgetJson].
  static final budgetJson = obx.QueryStringProperty<TripEntity>(
    _entities[3].properties[14],
  );

  /// See [TripEntity.status].
  static final status = obx.QueryStringProperty<TripEntity>(
    _entities[3].properties[15],
  );

  /// See [TripEntity.numberOfPeople].
  static final numberOfPeople = obx.QueryIntegerProperty<TripEntity>(
    _entities[3].properties[16],
  );

  /// See [TripEntity.coverImageUrl].
  static final coverImageUrl = obx.QueryStringProperty<TripEntity>(
    _entities[3].properties[17],
  );

  /// See [TripEntity.tagsJson].
  static final tagsJson = obx.QueryStringProperty<TripEntity>(
    _entities[3].properties[18],
  );

  /// See [TripEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<TripEntity>(
    _entities[3].properties[19],
  );

  /// See [TripEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<TripEntity>(
    _entities[3].properties[20],
  );
}
